name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  phpunit:
    name: "PHPUnit"
    runs-on: "ubuntu-20.04"

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.1"
          - "8.2"
          - "8.3"
        dependencies:
          - "highest"
          - "lowest"
        remove-annotations:
          - "yes"
          - "no"
        symfony-require:
          - "^3.0"
          - "^4.0"
          - "^5.0"
          - "^6.0"
        include:
          - php-version: 8.4
            symfony-require: "^5.0"
            composer-options: "--ignore-platform-req=php+" # TODO remove once phpspec/prophecy supports PHP 8.4
          - php-version: 8.4
            symfony-require: "^6.0"
            composer-options: "--ignore-platform-req=php+" # TODO remove once phpspec/prophecy supports PHP 8.4
          - php-version: 8.2
            symfony-require: "^7.0"
          - php-version: 8.2
            symfony-require: "^7.0"
            remove-annotations: "yes"
          - php-version: 8.3
            symfony-require: "^7.0"
          - php-version: 8.3
            symfony-require: "^7.0"
            remove-annotations: "yes"
          - php-version: 8.4
            symfony-require: "^7.0"
            composer-options: "--ignore-platform-req=php+" # TODO remove once phpspec/prophecy supports PHP 8.4

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "pcov"
          ini-values: "zend.assertions=1"
          tools: "flex"

      - name: "Remove remove-annotations if required"
        if: "${{ matrix.remove-annotations == 'yes' }}"
        env:
          SYMFONY_REQUIRE: "${{ matrix.symfony-require }}"
        run: |
          composer remove --no-update --dev doctrine/annotations

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v2"
        env:
          SYMFONY_REQUIRE: "${{ matrix.symfony-require }}"
        with:
          dependency-versions: "${{ matrix.dependencies }}"
          composer-options: "${{ matrix.composer-options }}"

      - name: "Run PHPUnit"
        run: "bin/phpunit --coverage-text"
